version: '3'
services:
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: zup
      MYSQL_USER: zup
      MYSQL_PASSWORD: zup
      MYSQL_DATABASE: contas
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./docker/data.sql:/docker-entrypoint-initdb.d/2-data.sql